# Site settings
name: Aya El Janoussi
title: Aya El Janoussi | Computer Science Engineering student
description: an ambitious Computer Science engineering student passionate about Data Science, Data Engineering, Data Analysis and AI
url: https://codingaya.github.io/
baseurl: ''
email: aya.eljanoussi@gmail.com
cover: https://codingaya.github.io/img/opening.png
logo: https://codingaya.github.io/img/emojis/technologist.png
resume: https://codingaya.github.io/resume.pdf
social:
  - title: email
    url: mailto:aya.eljanoussi@gmail.com
  - title: medium
    url: https://medium.com/@ayaeljanoussi
  - title: github
    url: https://github.com/codingaya
  - title: linkedin
    url: https://www.linkedin.com/in/aya-el-janoussi/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
